import { ScenarioType, SimulationParams } from '../types/simulation';

export const SCENARIO_PRESETS: Record<ScenarioType, Partial<SimulationParams>> = {
  'Normal Traffic': {
    scenario: 'Normal Traffic',
    attackProfile: 'HTTP Flood Simulation',
    botCount: 2500,
    distributionMode: 'Distributed',
    trafficIntensity: 'Very Low',
    trafficPattern: 'Constant',
    durationSeconds: 60,
    target: 'Demo Web Server',
    targetIp: '10.0.0.15',
    infrastructure: {
      serverCount: 2,
      serverCapacity: 'Standard',
      cpuCapacity: 60,
      ramCapacity: 60,
      networkCapacity: 70,
      databaseCapacity: 65,
      defenses: {
        rateLimiting: false,
        ipReputationFilter: false,
        cdn: false,
        webApplicationFirewall: false,
        loadBalancer: true,
        caching: true,
        autoScaling: false,
        trafficFiltering: false,
        challengePage: false,
        ddosProtectionService: false,
      },
    },
  },
  'Traffic Spike': {
    scenario: 'Traffic Spike',
    attackProfile: 'HTTP Flood Simulation',
    botCount: 25000,
    distributionMode: 'Distributed',
    trafficIntensity: 'Medium',
    trafficPattern: 'Sudden Spike',
    durationSeconds: 60,
    target: 'Online Store',
    targetIp: '10.0.1.42',
    infrastructure: {
      serverCount: 2,
      serverCapacity: 'Standard',
      cpuCapacity: 60,
      ramCapacity: 60,
      networkCapacity: 65,
      databaseCapacity: 60,
      defenses: {
        rateLimiting: true,
        ipReputationFilter: false,
        cdn: false,
        webApplicationFirewall: false,
        loadBalancer: true,
        caching: true,
        autoScaling: false,
        trafficFiltering: false,
        challengePage: false,
        ddosProtectionService: false,
      },
    },
  },
  'Flash Crowd': {
    scenario: 'Flash Crowd',
    attackProfile: 'Layer 7 Traffic Surge',
    botCount: 50000,
    distributionMode: 'Highly Distributed',
    trafficIntensity: 'High',
    trafficPattern: 'Wave',
    durationSeconds: 60,
    target: 'Streaming Platform',
    targetIp: '10.0.8.20',
    infrastructure: {
      serverCount: 4,
      serverCapacity: 'High',
      cpuCapacity: 75,
      ramCapacity: 75,
      networkCapacity: 80,
      databaseCapacity: 70,
      defenses: {
        rateLimiting: true,
        ipReputationFilter: false,
        cdn: true,
        webApplicationFirewall: false,
        loadBalancer: true,
        caching: true,
        autoScaling: true,
        trafficFiltering: false,
        challengePage: false,
        ddosProtectionService: false,
      },
    },
  },
  'DDoS Simulation': {
    scenario: 'DDoS Simulation',
    attackProfile: 'Layer 7 Traffic Surge',
    botCount: 250000,
    distributionMode: 'Highly Distributed',
    trafficIntensity: 'Extreme',
    trafficPattern: 'Burst',
    durationSeconds: 60,
    target: 'Public API',
    targetIp: '10.0.5.100',
    infrastructure: {
      serverCount: 4,
      serverCapacity: 'Standard',
      cpuCapacity: 60,
      ramCapacity: 60,
      networkCapacity: 50,
      databaseCapacity: 55,
      defenses: {
        rateLimiting: false,
        ipReputationFilter: false,
        cdn: false,
        webApplicationFirewall: false,
        loadBalancer: true,
        caching: false,
        autoScaling: false,
        trafficFiltering: false,
        challengePage: false,
        ddosProtectionService: false,
      },
    },
  },
  'Protected Infrastructure': {
    scenario: 'Protected Infrastructure',
    attackProfile: 'Mixed Traffic Simulation',
    botCount: 1000000,
    distributionMode: 'Highly Distributed',
    trafficIntensity: 'Overwhelming',
    trafficPattern: 'Adaptive',
    durationSeconds: 60,
    target: 'Banking Demo Platform',
    targetIp: '10.0.99.1',
    infrastructure: {
      serverCount: 8,
      serverCapacity: 'Enterprise',
      cpuCapacity: 90,
      ramCapacity: 90,
      networkCapacity: 95,
      databaseCapacity: 90,
      defenses: {
        rateLimiting: true,
        ipReputationFilter: true,
        cdn: true,
        webApplicationFirewall: true,
        loadBalancer: true,
        caching: true,
        autoScaling: true,
        trafficFiltering: true,
        challengePage: true,
        ddosProtectionService: true,
      },
    },
  },
  'Overloaded API': {
    scenario: 'Overloaded API',
    attackProfile: 'API Endpoint Flood',
    botCount: 100000,
    distributionMode: 'Centralized',
    trafficIntensity: 'High',
    trafficPattern: 'Gradual Increase',
    durationSeconds: 60,
    target: 'Public API',
    targetIp: '10.0.5.100',
    infrastructure: {
      serverCount: 2,
      serverCapacity: 'Low',
      cpuCapacity: 45,
      ramCapacity: 50,
      networkCapacity: 60,
      databaseCapacity: 40,
      defenses: {
        rateLimiting: false,
        ipReputationFilter: false,
        cdn: false,
        webApplicationFirewall: false,
        loadBalancer: true,
        caching: false,
        autoScaling: false,
        trafficFiltering: false,
        challengePage: false,
        ddosProtectionService: false,
      },
    },
  },
  'Gaming Server Attack Simulation': {
    scenario: 'Gaming Server Attack Simulation',
    attackProfile: 'UDP Flood Simulation',
    botCount: 250000,
    distributionMode: 'Distributed',
    trafficIntensity: 'Extreme',
    trafficPattern: 'Wave',
    durationSeconds: 60,
    target: 'Game Server',
    targetIp: '10.0.3.77',
    infrastructure: {
      serverCount: 4,
      serverCapacity: 'High',
      cpuCapacity: 80,
      ramCapacity: 80,
      networkCapacity: 60,
      databaseCapacity: 70,
      defenses: {
        rateLimiting: true,
        ipReputationFilter: false,
        cdn: false,
        webApplicationFirewall: false,
        loadBalancer: true,
        caching: false,
        autoScaling: false,
        trafficFiltering: true,
        challengePage: false,
        ddosProtectionService: true,
      },
    },
  },
  'E-commerce Peak Traffic': {
    scenario: 'E-commerce Peak Traffic',
    attackProfile: 'HTTPS Request Flood',
    botCount: 100000,
    distributionMode: 'Highly Distributed',
    trafficIntensity: 'High',
    trafficPattern: 'Multi-stage',
    durationSeconds: 60,
    target: 'Online Store',
    targetIp: '10.0.1.42',
    infrastructure: {
      serverCount: 4,
      serverCapacity: 'Standard',
      cpuCapacity: 65,
      ramCapacity: 65,
      networkCapacity: 70,
      databaseCapacity: 65,
      defenses: {
        rateLimiting: true,
        ipReputationFilter: false,
        cdn: true,
        webApplicationFirewall: true,
        loadBalancer: true,
        caching: true,
        autoScaling: true,
        trafficFiltering: false,
        challengePage: false,
        ddosProtectionService: false,
      },
    },
  },
  'Login Endpoint Pressure': {
    scenario: 'Login Endpoint Pressure',
    attackProfile: 'Login Flood',
    botCount: 50000,
    distributionMode: 'Centralized',
    trafficIntensity: 'Medium',
    trafficPattern: 'Burst',
    durationSeconds: 60,
    target: 'Authentication Service',
    targetIp: '10.0.2.11',
    infrastructure: {
      serverCount: 2,
      serverCapacity: 'Standard',
      cpuCapacity: 50,
      ramCapacity: 55,
      networkCapacity: 60,
      databaseCapacity: 50,
      defenses: {
        rateLimiting: false,
        ipReputationFilter: false,
        cdn: false,
        webApplicationFirewall: false,
        loadBalancer: true,
        caching: false,
        autoScaling: false,
        trafficFiltering: false,
        challengePage: false,
        ddosProtectionService: false,
      },
    },
  },
  'CDN Stress Scenario': {
    scenario: 'CDN Stress Scenario',
    attackProfile: 'HTTPS Request Flood',
    botCount: 500000,
    distributionMode: 'Highly Distributed',
    trafficIntensity: 'Extreme',
    trafficPattern: 'Random',
    durationSeconds: 60,
    target: 'University Portal',
    targetIp: '10.0.12.5',
    infrastructure: {
      serverCount: 4,
      serverCapacity: 'Standard',
      cpuCapacity: 70,
      ramCapacity: 70,
      networkCapacity: 80,
      databaseCapacity: 70,
      defenses: {
        rateLimiting: true,
        ipReputationFilter: true,
        cdn: true,
        webApplicationFirewall: true,
        loadBalancer: true,
        caching: true,
        autoScaling: false,
        trafficFiltering: false,
        challengePage: false,
        ddosProtectionService: false,
      },
    },
  },
};
